### ISSUE TITLE
Sciebo & GDrive Repository Sharing

### ISSUE THREAD

**Issue by juan-castrillon** [EdgeLab-FHDO/Edge-Diagnostic-Platform#10]
Hey Aly

I noticed I dont have access to the Google Drive folder for all Edge Related Projects that you showed me once at the beggining (You sent me just access to one file), also, as the professor mentioned in the meeting, I provide you with my sciebo credentials to be added to the repository there as well 

### ScieboKennung:  jucas001@fh-dortmund.de

I would think @theodorelu27 is in the same situation. I mention it because maybe all that info it will be useful for the interface description?

**Comment by alyhasansakr** [comment]
We moved everything to Sciebo, there is nothing important on Google Drive other than the Master Thesis pdf I just attached to the other ticket. The problem is, I cannot give you access to a Sciebo folder that I don't own, the professor has to do it himself.

Anyway, the only things that you are missing are the papers that we reference, which is not that important right now.

**Comment by juan-castrillon** [comment]
Ahh ok, then I guess I'll close the issue. Thanks!
