### ISSUE TITLE
Master as a Docker container

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Edge-Diagnostic-Platform#103]
It should be possible to run the main master application as a Docker container.

We need to do the following:

1. A Gradle task that creates the image and pushes it to a local Docker registry (hosted on a local machine) or directly to a local Docker cache (same as if you build an image directly on your local machine).
2. A GitHub action that creates the image and pushes it to a public Docker registry (when changes are pushed to the master branch).

Of course we still need the original Gradle run task that just runs the application directly.

**Comment by juan-castrillon** [comment]
After doing some research in avaiable plugins for this I think i will follow this structure for the gradle part:
- Create a `fatJar` task (Same as the one in client and server of my app) for the platform
- Manually define a dockerfile similar to the one in the app (Multistage build with gradle image and jre)
- Create a `buildImage` task that uses one of the available gradle plugins (either [this](https://bmuschko.github.io/gradle-docker-plugin) or [this](https://github.com/palantir/gradle-docker)) to create the docker image and have it in local cache
- Create a `dockerPushLocal` task that pushes to a locallly deployed repo (Specifying configuration in the `gradle.build` file)
- Create a `dockerPushRemote` task that pushes to a dockerhub repo (Specifying configuration in the `gradle.build` file)

I dont think we need a `dockerRunContainer` task or something similar.

Additionally, for the dockerhub part i will initially try it with a dummy account

**Comment by alyhasansakr** [comment]
OK, that should be good enough.
One more point to consider in case someone uses only the Docker image, how should the configuration be passed to a Docker container?

**Comment by juan-castrillon** [comment]
I am struggling with something related right now. The way we load the configuration file in the master makes it dependant on the path where java is executed (actually the way we load all files, e.g scenarios as well). So when creating the jar, running from the main directory worked but going to where the jar is and running there didnt. I managed to change that so that the jar reads from the default configuration file that is bundled inside as a resource. However, this makes it so a custom configuration file needs to be in the `resources` folder that is generated when the project is built, so a configuration file outside cannot be read (that would be an issue if we copy the config file in the dockerfile for example and try to run the platform passing the path as argument)

I thought we could limit the scope of where the config files can be located so inside the resources folder, create a `Configurations` folder in which we put all the config files. The platform then always reads from this folder (and only from this folder) and selects the configuration based on path relative from this folder. In that way, the jar will have that folder inside, and just passing a name (or relative path) argument will change the configuration (which can be done passing arguments to the container when running it)

What do you think? @alyhasansakr

**Comment by juan-castrillon** [comment]
Btw we could take the same approach with Scenarios. Have a folder in which they all need to be before creating the jar and then they can all be found and read in the container

**Comment by alyhasansakr** [comment]
@juan-castrillon 
The solution for that is to provide the full path for the required files (configuration or scenarios), I don't believe we need to specify a certain folder for them.
But I have another problem, if someone has only the Docker image and his own configuration and scenario files. How could they run a Docker container with these files?

**Comment by juan-castrillon** [comment]
They would need the whole source code too (what we have here in the repo). Then that would be copied into the the container where gradle will be run.

**Comment by juan-castrillon** [comment]
With respects to the paths you are right, the only exception would be the default configuration (because is set when no path argument is passed so the path is hardcoded). But I guess I can use a different way of loading (from jar or from files) according to whether the path argument was passed or not
