### ISSUE TITLE
Communication with Master

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Edge-Diagnostic-Platform#14]
What should we use for the connections client-master, server-master, client-server. The last one is application dependent, so we are interested only in the first two.
Examples of what we can use:
- REST.
- MQTT.
- ROS.
- Our Own (implementation using SOCKET directly).
Compare between these solutions or propose others.

**Comment by theodorelu27** [comment]
I tried to compare REST, MQTT, ROS, CoAP, and implementing our own socket

MQTT
-	Over TCP
-       Broker-Client configuration
-	Requires handshakes before communication can be done
-	Widely used in IoT applications
CoAP
-	Over UDP
-	Adds acknowledgement but does not verify message integrity
-	Similar to HTTP
-	Standard is still maturing
REST
-	Widely used
-	Independent
-	Stateless
ROS
-	Master-slave configuration
-	Uses TCP/UDP depending which one is more suitable for the transport
-	Designed for isolated network, so we need to implement firewall or other isolation method, connection need to be initiated by the Master
Socket implementation
-	Low to no dependency to external library/framework
-	We need to implement and handle network issues ourselves

I think for Client-Master, it is better to use REST, to allow applications where foreign device are involved, it wouldn't have too much trouble with the firewall configurations

For Server-Master, since the Master and Server should be part of the same server and I think the system can benefit from the persistent session if it changes due to the Server connecting to a Client, so I think we can try MQTT .

**Comment by alyhasansakr** [comment]
@theodorelu27 
What is the exactly the advantage of MQTT over REST?
If we are going with REST for clients, then might as well do so for the servers, servers may be running on foreign devices as well (in case someone provides an infrastructure where we have limited access to).

**Comment by theodorelu27** [comment]
@alyhasansakr 
initially I chose MQTT because it has these following advantages over an established network
- it is lightweight, because it carries less stuff in its headers and designed to carry only small amount of data which suits our use case in the master-server application
- the connection is permanent which relates to less resource needed during reconnections, so we can configure the server to report more often
However, MQTT needs a broker, which I think could be implemented within the Master device to make it a sole subscriber

since our system might involve foreign devices however, I agree that using REST would be a much safer option to ensure ubiquitousness

**Comment by alyhasansakr** [comment]
Good, then we go with REST.
