### ISSUE TITLE
Compare Build Tools

### ISSUE THREAD

**Issue by juan-castrillon** [EdgeLab-FHDO/Edge-Diagnostic-Platform#2]
Gradle, Maven or Ant?

**Comment by juan-castrillon** [comment]
Apache Maven was released in 2004, and now it is one of the most popular choices for Java developers (especially for server-side development). Many projects, both old and new, use Maven as a build tool because of its powerful dependency management possibilities.

Maven follows the Convention Over Configuration concept which means that a developer needs to specify only unconventional aspects of the application, and all standard aspects work by default.

Gradle is a new tool compared to Ant and Maven. It was released in 2007 and is now standard for Android applications. Also, developers use it for server and desktop development. Gradle aims to “combine the power and flexibility of Ant with the dependency management and conventions of Maven into a more effective way to build.”

**Comment by alyhasansakr** [comment]
After some research I can say the following:
- Ant is too "barebones", so it is not a choice for us.
- Gradle is faster than Maven (in bigger projects).
- Maven is easier to learn than Gradle, because of its strict structure.
- Gradle is more flexible and powerful than Maven, because it uses Domain-Specific Language (DSL).

My recommendation is Gradle, since we are learning anyway it doesn't matter as much if it is harder to learn.

**Comment by juan-castrillon** [comment]
I agree with the choice of Gradle. Even though it may take a little more time to learn, I believe that the simplicity of the build files, the flexibility, the community support and specially the [speed](https://gradle.org/gradle-vs-maven-performance/) make it worth it. 

Also, if we feel the need to justify it even more, even though [this](https://www.slideshare.net/ZeroTurnaround/java-build-tools-part-2-a-decision-makers-guide) data is a bit old (2014) I believe shows the many advantages

If we both agree, should I proceed to close the issue?

**Comment by alyhasansakr** [comment]
yes, I will mention it in #1
