### ISSUE TITLE
Logging Solution

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Edge-Diagnostic-Platform#28]
We want to find a logging solution that allows us to log data over network, that is from multiple docker containers to a component on our server, it needs to be extensible and lightweight, supporting visualization is a bonus.

Candidates would be (not exactly sure if we are looking at the right thing): kibana - Grafana - Log4j

In case there is no ready solution that we can use, we will implement our own.

**Comment by juan-castrillon** [comment]
After doing some research, I think the best approach would be to:
- In the app(s) use [SLF4J](http://www.slf4j.org/) in combination with either [Logback](http://logback.qos.ch/) or [Log4J2](https://logging.apache.org/log4j/2.x/index.html). The use of SLF4J would allow some flexibility in the design allowing us to later change the logger if needed. 

- As stated for example [here](https://stackoverflow.com/questions/32280232/log4j-container-logging-on-kubernetes), and seing that kubernetes is easy to integrate with [Kibana and the ELK stack](https://kubernetes.io/docs/tasks/debug-application-cluster/logging-elasticsearch-kibana/), the integration with the whole [ELK Stack](https://www.elastic.co/elastic-stack) could be done directly, adding the visualisation and container support.  

- Another idea would be to use logback (or log4j) configuration to use TCP appender to send logs to a remote Logstash instance via TCP protocol ,and then using the rest of the stack to visualize the data. The whole ELK also provides many other options to achieve reading and showing the logs, like [this](https://www.baeldung.com/java-application-logs-to-elastic-stack), providing also a way to [ direcly interface log4j](https://github.com/logstash/log4j-jsonevent-layout) . However all of this ideas, would require to install ELK on the server running the master, is that ok?

I am kinda lost, because its the first time I work on something like this, so your feedback @alyhasansakr  would be very much appreciated. Am I looking in the right direction?

**Comment by alyhasansakr** [comment]
You are on the right track.

I agree with SLF4J and Logback for applications.
I don't want something that is Kubernetes dependent, it is better if we go with Logstash solution.
And of course ELK is necessary here.

This is all we need to know here, I will write another issue for implementation when the time is right.
