### ISSUE TITLE
AdvantEdge Integration

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Edge-Diagnostic-Platform#29]
Implement a controller for AdvantEdge. It uses REST to send commands to AdvantEdge.

The main functionalities that we need are:
- Deploy an AdvantEdge scenario.
- Terminate an AdvantEdge scenario.

Tests may not include an actual AdvantEdge deployment, only check if the REST requests are sent.

**Comment by juan-castrillon** [comment]
After doing some research, there is two ways of achieving this, as can be seen [here](https://github.com/InterDigitalInc/AdvantEDGE/wiki/API-Documentation#interfacing-with-api) : 

1.  Make the requests from software directly to AdvantEDGE HTTP endpoints. This would integrate easily into our program, and the APIs are ver well defined [here](https://github.com/InterDigitalInc/AdvantEDGE/wiki/api-sandbox-ctrl) and [here](https://github.com/InterDigitalInc/AdvantEDGE/wiki/api-platform-ctrl) for the functionalities we need right now (and probably the ones we would need eventually) . The only downside i find is that in the AdvantEDGE API documentation, it says 
> This method works but is not optimal

2. The recommended method by AdvantEDGE is to use a [swagger code generator](https://github.com/swagger-api/swagger-codegen) to generate a client package inside our project based only on the YAML files describing the API. Although, this looks promising, I've tried it and I think it has two downsides: First, it will add all the functionality for each YAML file, that means a lot of files and code we wouldnt use. Second, it apparently bases its JSON implementation on the GSON library, so in order to have only one JSON library, the current implementation with Jackson would have to be changed.

What do you think @alyhasansakr , is it worth the complexity of the generated java package api over the simple request making?

**Comment by alyhasansakr** [comment]
The first solution is optimal for us, go with it.
