### ISSUE TITLE
Infrastructure Manager Design

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Edge-Diagnostic-Platform#3]
Produce UML diagrams, start with:
- Class Diagram.
- Sequence Diagrams.

**Comment by alyhasansakr** [comment]
This is just the initial component diagram, what we need here is a class diagram for the main component (infrastructure manager) as well as sequence diagrams for each interface in the component diagram.

**Comment by alyhasansakr** [comment]
[QoS_Aware_Score_Based_Edge_Resource_Allocation_Model.pdf](https://github.com/EdgeLab-FHDO/Edge-Diagnostic-Platform/files/5010088/QoS_Aware_Score_Based_Edge_Resource_Allocation_Model.pdf)
for reference about what we already did before.

**Comment by alyhasansakr** [comment]
we do class diagram first

**Comment by theodorelu27** [comment]
![image](https://user-images.githubusercontent.com/12758306/89110351-22848500-d44a-11ea-9c53-4adc4e1dcbcd.png)

This is my first draft based on the Solution Model, I think it still lacks the detailed properties of each classes.
I assumed that the main Infrastructure Manager class would be implemented as a singleton that the Clients (user devices) would refer to and the Nodes (edge devices) would report to
so the provided edge will be provided by the Infrastructure Manager but making connection would be handled by the user device itself

**Comment by alyhasansakr** [comment]
Great, but I am more interested in the classes than attributes and methods, we can leave attributes and methods for now. Also, we need to mention more classes for almost every abstract entity, for example, a connection to a client should also be a class. Other examples are: the input receiver, the output producer, the match-making algorithm, ...

**Comment by alyhasansakr** [comment]
Let me provide some help:

You got the first class right; there has to be a singleton class called **InfrastructureManager** and it manages clients and nodes. However, a node may exist without it being announced to the master, also its connection to the master has a lot of parameters and functions, in this case we should have both a **Node** and **NodeConnection** classes, same applies for **Client** and **ClientConnection**. As you can see there is a common behavior between the two connections, so we need a **Connection** abstract class that is the super of both of them.

Another point is events and scenarios, looking at the requirement, there are different types of events, so again one super class **Event** and a class for each type. And at least one **Scenario** class must exists, we may need other classes for scenarios like **ScenarioInstance** to allow us to run more than one scenario at the same time, but really the requirements in this part are not clear enough yet. I would say we will also need a **Simulation** class here.

The requirements also mention the ability to deploy nodes and clients, so at least one **Deployment** class must be included. It also mentions different ways to deploy a deployment, thus we may need a **DeploymentApplicator** class as well.

To control this infrastructure manager we need actions, so an **Action** super class along with different classes for each possible action would be useful.

For the output of a simulation, we could have a **Measurement** class which can be sampled using a **Sampler** super class which may be a **LoggerSampler** or a **DisplaySampler**.

Match-making is a significant function in our system, so a **MatchMakingAlgorithm** super class must be considered.

This is just a short list of recommendations, you may get more when you set down and think about it. It is always better to get as many classes as you can before implementation, otherwise, there is a high chance of mixing functionalities, and then it will take more time to untangle these mixed classes than to define it correctly now.

By the way, I don't want to include programming interfaces in our class diagram, so interfaces like **Assignable**, **Printable**, **Cancelable**, and so on, are expected to be done as part of refactoring, because of how hard it is to identify them during design. The classes we include in our class diagram are actual classes in programming not interfaces.

**Comment by theodorelu27** [comment]
![image](https://user-images.githubusercontent.com/12758306/89196659-cedd7d00-d5aa-11ea-91a2-465f1219fc1e.png)

I've made a second draft from your before I read the second feedback where I tried to break down the responsibilites further and let the main components communicate with each other through connection interfaces
I'd update this soon with the recent feedback, but is how I break down the responsibility in the right direction?

**Comment by alyhasansakr** [comment]
Yes, that is how it should be done, lets see how it looks like when you add other classes as well.

**Comment by juan-castrillon** [comment]
Also, I think it would help us a lot to have a class (or super class) for resources, given that functional requirements 3, 4 and 5 all require objects of that kind (in that order of ideas, performance parameters or events can be their own classes and attributes of this kind of objects). What do you think?

**Comment by theodorelu27** [comment]
![Infrastructure Manager CD (1)](https://user-images.githubusercontent.com/12758306/89349859-32e96980-d6af-11ea-81e5-e15e9f8de0ee.png)

This is my progress so far, I'd continue tomorrow, especially on Events, Scenario, Measurements, Sampler, Simulations, and to find more classes that I missed
it might be hard to see, so here's the link to the draw.io: https://drive.google.com/file/d/1cYX-HmyzT26P_yKxtkqH0qERqw8DJrNh/view?usp=sharing

Thank you for the help and feedbacks, I like Juan's idea since I already added the Node Pool and Connection History as a resource for the Master (Infrastructure Manager) so I added it as a general component for the applications

**Comment by alyhasansakr** [comment]
@theodorelu27 put your final thoughts in and send us your final version tomorrow, no need to be complete or anything, just what you got so far.

**Comment by theodorelu27** [comment]
![Infrastructure Manager CD (3)](https://user-images.githubusercontent.com/12758306/89473539-6695c380-d783-11ea-965e-7ab919316ce9.png)

This is my latest draft, I tried to add all possible classes in the requirement, component diagram, and previous works, so I hope I didn't miss anything
- classes that doesn't have specific implementation such as Measurement and GUI (I made GUI inherits the Visualization superclass so later we can implement as text with JSON or something) have been abstracted for now
- the classes in dotted borders are redudants to ease reading
- I added ScenarioContainer for implementation of running multiple scenarios

What I haven't added because I wasn't sure:
- CloudNode: do we consider in this context, the possibility of falling back to cloud in case there's no suitable Edge in the matchmaking?
- Platform and/or possibility of abstracting Infrastructure Manager to fulfill Non-functional Requirement

**Comment by alyhasansakr** [comment]
Good job, I will take it from here, I will do some refinement and create issues as required.

**Comment by theodorelu27** [comment]
okay, do update me if you need me to give you edit permission to the diagram

**Comment by alyhasansakr** [comment]
I don't think we need to change anything else here.
@theodorelu27 make a new Wiki page (anywhere) and just add this image as it is, we don't need to say anything else there.

**Comment by theodorelu27** [comment]
@alyhasansakr done on https://github.com/EdgeLab-FHDO/Edge-Diagnostic-Platform/wiki/Class-Diagram
