### ISSUE TITLE
Wiki Initial Content

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Edge-Diagnostic-Platform#4]
Add project description along with illustrative diagrams to the main page of the wiki.

**Comment by juan-castrillon** [comment]
I started with the documentation as we talked on Monday @alyhasansakr .

If you check the wiki, here is the changes that i made:

- Added a home page with a description of the platform and a context diagram
- Created a general structure for the documentation: Filled some parts but the ones with a bullet point (- [ ] a) are still to be made

What do you think? Am I too detailed or not enough? Any feedback would be greatly appreciated.

**Comment by alyhasansakr** [comment]
That is fantastic! just go on.

**Comment by juan-castrillon** [comment]
As of right now, the whole [Using the platform](https://github.com/EdgeLab-FHDO/Edge-Diagnostic-Platform/wiki/Using-the-platform) section is almost complete. Only thing missing is the AdvantEDGE [example](https://github.com/EdgeLab-FHDO/Edge-Diagnostic-Platform/wiki/Running-with-AdvantEDGE#example), I wanted to do it with a real advantEdge scenario, generated in the platform, but I will have to wait for a bit because I am having some issues with my deployment and dont really seem to figure out a way to fix it, so I will do a clean install.

Any feedback would be greatly appreciated. I will start now with the [Basics](https://github.com/EdgeLab-FHDO/Edge-Diagnostic-Platform/wiki/Basics) section.

**Comment by juan-castrillon** [comment]
Quick update, I was able to kind of fix my AdvantEDGE deployment. (Almost because it never turns green, always says `meep-postgis0: Pending`), therefore I could at least show some example in advantEdge client (Creating the scenario for real but not deploying)

**Comment by juan-castrillon** [comment]
As of right now, the documentation is on the following:
- Basics section in the wiki is finished (I based myself  sometimes on what i am writing on the thesis)
- Using the platform section is also finished (With the current state of the platform)
- README now has a quick introduction and a link to the wiki

Still missing:
- Software Development part of the wiki: I am waiting on this according to what you told me @alyhasansakr about waiting on the modeling.

If we are to wait until the refactor to model, I would say we are ready to close this issue. Let me know what you think..

**Comment by alyhasansakr** [comment]
That is more than enough for now.
