### ISSUE TITLE
CPU Limit Command format: RestOutput.java / addToLimitList 

### ISSUE THREAD

**Issue by JeanValjean17** [EdgeLab-FHDO/Edge-Diagnostic-Platform#46]
When using the limit CPU command like this: _limit edge1 100000 200000_, the limit command will be stored incorrectly. In the addToLimitList method, these two values are multiplied. However, using the command like this: _limit edge1 0.5 200000_ works. Which of the two formats should be the correct one? What I found according to how the limit.sh script works is: If it's the first format, the multiplication in quota_ms (RestOutput.java:addToLimitList) should be deleted and the input should be concatenated like this: 100000_200000.

**Comment by alyhasansakr** [comment]
@JeanValjean17 
I believe it was made this way to expose the important information to the user (number of cores) instead of a calculation that (while easy) some people may not get it from the first time.

Another reason is that the ideal use of it is "limit edge1 0.5", completely omitting the period time (defaults to 100000).
